apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-pod-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: progettone.it
    http:
      paths:
      - backend:
          service:
            name: client-pod
            port:
              number: 80
        path: /
        pathType: Prefix